name: Automerge
on:
  pull_request:
    types:
      - labeled
permissions:
  contents: write
  pull-requests: write
jobs:
  automerge:
    if: github.event.label.name == 'automerge'
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
